#+title: TEIVR example using JSF + NPE

* Data

The data is sourced from the following paper:

  - https://doi.org/10.1038/s41564-022-01105-z

Specifically, we use patients 432192, 443108, 444332, 444391, 445602, and 451152.

The processed data is stored in the =data= directory.

* Model


** Stoichiometric

Here are the reactant and products as needed by the hybrid model and
the flows as needed by the CTMC model.

|          | *Reactants* |     |     |     |      | *Products* |     |     |     |     | *Flow*      |     |     |     |     | 
|----------+-------------+-----+-----+-----+------+------------+-----+-----+-----+-----+-------------+-----+-----+-----+-----|
| *Rate*   |         $T$ | $E$ | $I$ | $V$ | $R$  |        $T$ | $E$ | $I$ | $V$ | $R$ |         $T$ | $E$ | $I$ | $V$ | $R$ |
|----------+-------------+-----+-----+-----+------+------------+-----+-----+-----+-----+-------------+-----+-----+-----+-----|
| $\beta$  |          1  |   . |   . |   1 |   .   |          . |   1 |   . |   1 |   . |         -1|    1 |   . |   . |   . |
| $\kappa$ |          .  |  1  |   . |   . |   .   |          . |   . |   1 |   . |   . |          .|   -1 |   1 |   . |   . |
| $\delta$ |          .  |   . |   1 |   . |   .   |          . |   . |   . |  .  |   . |          .|    . |  -1 |   . |   . |
| $\pi$    |          .  |   . |   1 |   . |   .   |          . |   . |   1 |   1 |   . |          .|    . |   . |   1 |   . |
| $c$      |          .  |   . |   . |   1 |   .   |          . |   . |   . |   . |   . |          .|    . |   . |  -1 |   . |
| $\Phi$   |          1  |   . |   1 |   . |   .   |          . |   . |   1 |   . |   1 |         -1|    . |   . |   . |   1 |
| $\rho$   |          .  |   . |   . |   . |   1   |          1 |   . |   . |   . |   . |          1|    . |   . |   . |  -1 |

** Differential equations

Here are the differential equations used by the ODE model:

$\frac{dT}{dt} = - \beta V T - \Phi I T + \rho R$,

$\frac{dE}{dt} = \beta V T - k E$,

$\frac{dI}{dt} = k E - \delta I$,

$\frac{dV}{dt} = \pi I - c V$,

$\frac{dR}{dt} = \Phi I T - \rho R$.


* Simulation and Inference

To run the inference on the data, you first describe the data in a file, e.g., [[file:./data/432192.ssv]]. 
Then, you set the inference settings in the file [[file:./config/cli-refractory-tiv-jsf.toml]].

To run the inference, use the following command:
#+begin_src sh
  python COVID_TEIVR_NPE.py
#+end_src

This will run the inference for each patient in the data directory independently, and pickle the results.


To run the Analysis, use the following command:
#+begin_src sh
  python COVID_TEIVR_Predict.py
#+end_src

Look in the output directory for the results.

* Environment

** REQUIRED: Setting up the project and virtual environment

*IMPORTANT:* You MUST set up a virtual environment before running any code in this project.

#+begin_src sh

# Clone the repository
git clone -b npe-light https://github.com/tomkimpson/JSFGermano2024.git <any_folder_name>

cd <any_folder_name>/TEIVR_Results/particle-filter-example-tiv_covid/

# Setup virtual environment
python3 -m venv venv-npe
source venv-npe/bin/activate

# Install required packages. The [[file:./requirements.txt][requirements.txt]] and [[file:./requirements_npe.txt][requirements_npe.txt]] files 
contains a description of the packages (and versions) needed to run this. Use the following commands to create and set up the virtual environment.

pip install -r requirements.txt
pip install -r requirements_npe.txt

# Quick test script to verify NPE setup is correct.
python test_npe_setup.py

# Run the script with default parameters
chmod +x run_npe.sh
./run_npe.sh

#+end_src

*NOTE:* The requirements.txt file includes jsf==0.1, which will be installed from PyPI. If you need to use a local/development copy of JSF instead, you will need to clone the JSF repository from GitHub and install it using =pip install -e /path/to/jsf=.


--------------------------------------------------------------------------------
The model is written in [[file:./src/tiv.py]]. The model is defined as a =jsf= method. 

- threshold parameter, \Omega, is set here: threshold = 100
- Stoichiometric matricies are defined in the attributes =_nu_reactants= and =_nu_products=
- the propensity functions are contained in _rates(self, x, theta, time)
- in update, _my_opts defines 'EnforceDo', the time step, 'dt', and the switch
  between the CTMC and ODE models for each state variable, as 'SwitchingThreshold'



The use of the particle filter is configured by the file [[file:./config/cli-refractory-tiv-jsf.toml]].
This file contains the following information:
- the number of particles to use in the particle filter
- the number of iterations to run the particle filter for
- the state parameters initial values
- the prior distributions for the parameters
- the *observation model*

--------------------------------------------------------------------------------
* TO GENERATE THE FIGURES
--------------------------------------------------------------------------------
 
